#!/usr/bin/env python3
"""A real cache + jobs + replay demo. See docs/guides/SAAS_DEMO.md.

Uses the bundled native Python client, the standard library, and a KuttiDB
binary. Starts and stops only its own child in a fresh temporary directory.
"""

import argparse
import csv
import hashlib
import io
import json
import os
from pathlib import Path
import platform
import shutil
import signal
import subprocess
import sys
import tempfile
import time
from datetime import datetime, timezone

# Repository checkout, or the client shipped beside this file in demo.tar.gz.
SOURCE = Path(__file__).resolve().parent.parent / "src"
if (SOURCE / "kuttidb_client.py").is_file():
    sys.path.insert(0, str(SOURCE))
from kuttidb_client import KuttiDBClient, KuttiDBError


def require(condition, message):
    # These checks must still run with PYTHONOPTIMIZE=1.
    if not condition:
        raise RuntimeError(message)


def resolve_server(requested):
    if requested:
        found = shutil.which(requested)
        if found:
            return Path(found).resolve()
        raise RuntimeError(f"Server not executable: {requested}")
    candidates = [SOURCE.parent / "kuttidb", shutil.which("kuttidb"),
                  Path.home() / ".local/bin/kuttidb"]
    for candidate in candidates:
        if candidate and Path(candidate).is_file() and os.access(candidate, os.X_OK):
            return Path(candidate).resolve()
    raise RuntimeError("KuttiDB not found. Run make, or pass --server /path/to/kuttidb.")


def rss_mib(pid):
    """Sample this child only; RSS is not a whole-machine or peak measurement."""
    try:
        result = subprocess.run(["ps", "-o", "rss=", "-p", str(pid)],
                                capture_output=True, text=True, timeout=2, check=True)
        return int(result.stdout.strip()) / 1024
    except (OSError, ValueError, subprocess.SubprocessError):
        return None


class DemoServer:
    def __init__(self, binary, directory):
        self.socket = str(directory / "db.sock")
        self.command = [str(binary), "7379", str(directory / "db.wal"),
                        "--unix-path", self.socket, "--no-tcp",
                        "--durability", "always", "--max-memory-mb", "16",
                        "--max-clients", "8", "--threads", "1"]
        self.process = None
        self.log = tempfile.TemporaryFile(mode="w+b")

    def connect(self):
        return KuttiDBClient(unix_path=self.socket, timeout=2)

    def start(self):
        self.process = subprocess.Popen(self.command, stdin=subprocess.DEVNULL,
                                        stdout=self.log, stderr=self.log)
        deadline = time.monotonic() + 10
        while time.monotonic() < deadline:
            if self.process.poll() is not None:
                break
            try:
                with self.connect() as db:
                    if db.health():
                        return
            except (OSError, KuttiDBError):
                pass
            time.sleep(0.03)
        self.stop()
        self.log.seek(0)
        detail = self.log.read().decode(errors="replace")[-3000:]
        raise RuntimeError("Demo server did not become ready:\n" + detail)

    def kill(self):
        require(self.process is not None and self.process.poll() is None,
                "Demo server exited before the crash check")
        self.process.kill()
        self.process.wait(timeout=5)

    def stop(self):
        if self.process is not None and self.process.poll() is None:
            self.process.terminate()
            try:
                self.process.wait(timeout=5)
            except subprocess.TimeoutExpired:
                self.process.kill()
                self.process.wait(timeout=5)


def run_demo(server, say):
    server.start()
    say("KuttiDB / one server. Three capabilities.")
    say("LOCAL    Private socket. Temporary data. Durable writes.")
    with server.connect() as db:
        db.queue_declare("reports", durable=True, max_depth=10)
        db.stream_declare("report.events", partitions=1, max_bytes=1 << 20)
        db.put("report:42", b"queued", ttl=300)
        require(db.get("report:42") == b"queued", "Cache read did not match")
        say("CACHE    report:42 -> queued")

        first_id = db.queue_publish("reports", b"report:42")
        job = db.queue_consume("reports")
        require(job and job["message_id"] == first_id and job["value"] == b"report:42",
                "Worker did not receive report:42")
        # A tiny, real report generated by the worker. No external side effects.
        report = io.StringIO()
        writer = csv.writer(report)
        writer.writerow(["customer", "total"])
        writer.writerows([("Ada", 42), ("Lin", 19), ("Sam", 27)])
        require(len(list(csv.reader(io.StringIO(report.getvalue())))) == 4,
                "Worker produced an invalid report")
        db.put("report:42", b"ready: 3 rows", ttl=300)
        require(db.get("report:42") == b"ready: 3 rows", "Ready status did not match")
        say("WORKER   Generated report:42 (3 CSV rows)")

        event = b'{"report":42,"status":"ready","rows":3}'
        position = db.stream_append("report.events", event, key="report:42")
        require(db.queue_ack("reports", job["id"]), "Worker ACK failed")
        require(db.queue_stats("reports")["depth"] == 0, "ACK did not drain the queue")
        say("QUEUE    Job acknowledged. Queue drained.")
        say(f"STREAM   report.ready appended at offset {position['offset']}")

        pending_id = db.queue_publish("reports", b"report:43")
        pending = db.queue_consume("reports", visibility=30)
        require(pending and pending["message_id"] == pending_id, "Second job missing")
        say("WORKER   Picked up report:43; no ACK yet.")
        memory = rss_mib(server.process.pid)
        say("MEMORY   " + (f"{memory:.1f} MiB server RSS (sample, not peak)"
                            if memory is not None else "RSS unavailable on this host"))
        say("CRASH    Killing this demo's server with SIGKILL...")
        # Keep the delivery connection open at the kill; ordinary disconnect
        # cleanup must not stand in for crash redelivery.
        server.kill()

    server.start()
    say("RESTART  Reopened the same data directory.")
    with server.connect() as db:
        require(db.get("report:42") == b"ready: 3 rows", "Cache state failed recovery")
        say("CACHE    report:42 -> ready: 3 rows")
        recovered = db.queue_consume("reports")
        require(recovered and recovered["message_id"] == pending_id
                and recovered["value"] == b"report:43" and recovered["redelivered"],
                "Unacknowledged job did not recover with its original identity")
        require(db.queue_ack("reports", recovered["id"]), "Recovered job ACK failed")
        require(db.queue_consume("reports") is None, "An acknowledged job reappeared")
        say("QUEUE    report:43 redelivered; report:42 stays ACKed.")
        records = db.stream_fetch("report.events", offset=position["offset"])
        require(len(records) == 1 and records[0]["value"] == event
                and records[0]["offset"] == position["offset"], "Event replay failed")
        say(f"REPLAY   report.ready recovered at offset {records[0]['offset']}")
    say("PASS     Cache + jobs + replay. All recovery checks passed.")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--server", default=os.environ.get("KUTTIDB_SERVER"))
    parser.add_argument("--delay", type=float, default=0,
                        help="presentation pause between lines, in seconds (0..2)")
    parser.add_argument("--record", type=Path, help="save a successful run as replay JSON")
    args = parser.parse_args()
    if not 0 <= args.delay <= 2:
        parser.error("--delay must be between 0 and 2")
    events = []
    started = time.monotonic()

    def say(line):
        events.append({"at": round(time.monotonic() - started, 3), "text": line})
        print(line, flush=True)
        if args.delay:
            time.sleep(args.delay)

    # SIGTERM during the demo also reaches the normal child cleanup path.
    def interrupted(signum, frame):
        raise KeyboardInterrupt

    signal.signal(signal.SIGTERM, interrupted)
    try:
        binary = resolve_server(args.server)
        # Short paths also fit macOS's Unix-socket pathname limit. mkdtemp
        # creates an owner-only directory; no existing server/data is touched.
        with tempfile.TemporaryDirectory(prefix="kutti-demo-", dir="/tmp") as tmp:
            server = DemoServer(binary, Path(tmp))
            try:
                run_demo(server, say)
            finally:
                server.stop()
                server.log.close()
        say("CLEANUP  Demo server stopped. Temporary data removed.")
        if args.record:
            args.record.write_text(json.dumps({
                "schema": 1, "recorded_at": datetime.now(timezone.utc).isoformat(),
                "platform": f"{platform.system()} {platform.release()} / {platform.machine()}",
                "server_sha256": hashlib.sha256(binary.read_bytes()).hexdigest(),
                "durability": "always", "threads": 1,
                "note": "Real local demo run. RSS is a sample, not a benchmark or peak. "
                        "SIGKILL tests process-crash recovery, not disk or machine loss.",
                "events": events,
            }, indent=2) + "\n")
        return 0
    except (OSError, RuntimeError, KuttiDBError, subprocess.SubprocessError) as error:
        print(f"Demo failed: {error}", file=sys.stderr)
        return 1
    except KeyboardInterrupt:
        print("Demo interrupted; its server and temporary data were cleaned up.", file=sys.stderr)
        return 130


if __name__ == "__main__":
    sys.exit(main())
